[package]

name = "tweetnacl"
version = "0.1.0"
authors = [ "Andreas Ots <qrpth@qrpth.eu>" ]

[[lib]]

name = "tweetnacl"

[dependencies.crockford-base32]

git = "https://github.com/andreasots/crockford-base32"
